### ISSUE TITLE
Error: "No options found"

### ISSUE THREAD

**Issue by GamePlayer-8** [zolagonano/torbridge-cli#1]
Hello,

after compiling your project, I'm getting:

```
torbridge-cli       
Getting available transports from BridgeDB
Error: "No options found"
```

The software is run inside of container.

**Comment by zolagonano** [comment]
Hi, thanks for reporting the issue, I have fixed it in https://github.com/zolagonano/torbridge-cli/commit/3f5ea59a0aec561aea50301befb4dc186c5673d0

Also the new version is published on crates.io
