### ISSUE TITLE
Integration with rdsys.

### ISSUE THREAD

**Issue by GamePlayer-8** [zolagonano/torbridge-cli#3]
Hey,

Is there by any chance an option to integrate bridge fetching into [rdsys](https://gitlab.torproject.org/tpo/anti-censorship/rdsys) for wider distribution?

**Comment by zolagonano** [comment]
I looked into it. The cli app fetches the bridges from bridges.torproject.org which now uses rdsys instead of bridgeDB.

https://forum.torproject.org/t/tor-project-new-bridgedb-version-using-rdsys/2335

**Comment by GamePlayer-8** [comment]
Ah alright, closing.
